apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage-dependabot
  description: test 2
  annotations:
    github.com/project-slug: backstage-tester/test-backstage-dependabot
    exposure: internal
    pii: "true"
    pci: "false"
    phi: "true"
    ai: "false"
    bank-device: na
    tier: "1"
spec:
  type: website
  lifecycle: legacy
  owner: group:default/security-platform
  system: system:default/examples
